
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291434
     no. of nonzeroes in lower triangle of a =        21240251
     no. of nonzeroes in the factor l        =       251366246
     ratio of nonzeroes in factor (min/max)  =          0.8618
     number of super nodes                   =            6328
     maximum order of a front matrix         =            3930
     maximum size of a front matrix          =         7724415
     maximum size of a front trapezoid       =         4943940
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.1954D+11
     no. of floating point ops for solve     =      9.7848D+08
     ratio of flops for factor (min/max)     =          0.7911
     ratio of allocated memory (max/min)     =          1.4355
     number of positive pivots               =          291434
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.109375        0.110825
     time (cpu & wall) for ordering          =        0.718750        0.747307
     time (cpu & wall) for other matrix prep =        0.109375        0.130492
     time (cpu & wall) for value input       =        0.265625        0.275124
     time (cpu & wall) for matrix distrib.   =        0.625000        0.645929
     time (cpu & wall) for numeric factor    =        7.468750        7.830018
     computational rate (gflops) for factor  =       56.172902       53.581152
     time (cpu & wall) for numeric solve     =        0.421875        0.731082
     computational rate (gflops) for solve   =        2.319369        1.338406
     effective I/O rate (GB/sec) for solve   =        8.641010        4.986347

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                90-   0      68354048.      522. MB     177192330.     1352. MB
                90-   1      58949632.      450. MB     156453094.     1194. MB
                90-   2      67633152.      516. MB     179484857.     1369. MB
                90-   3      62783488.      479. MB     168985564.     1289. MB
                94-   0       7667712.       58. MB      15279934.      117. MB
                94-   1       6127616.       47. MB      12198054.       93. MB
                94-   2       7208960.       55. MB      14363412.      110. MB
                94-   3       6914048.       53. MB      13792766.      105. MB
                95-   0        655360.        5. MB        654409.        5. MB
                95-   1        622592.        5. MB        616170.        5. MB
                95-   2        622592.        5. MB        592068.        5. MB
                95-   3        589824.        4. MB        558607.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:     288129024.     2198. MB     740171265.     5647. MB


  Solver Memory allocated on core    0       =      336.845 MB
  Solver Memory allocated on core    1       =      236.564 MB
  Solver Memory allocated on core    2       =      277.131 MB
  Solver Memory allocated on core    3       =      234.659 MB
  Total Solver Memory allocated by all cores =     1085.199 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291434
     no. of nonzeroes in lower triangle of a =        21257477
     no. of nonzeroes in the factor l        =       250723862
     ratio of nonzeroes in factor (min/max)  =          0.8602
     number of super nodes                   =            6321
     maximum order of a front matrix         =            4599
     maximum size of a front matrix          =        10577700
     maximum size of a front trapezoid       =         5576130
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.2464D+11
     no. of floating point ops for solve     =      1.9544D+09
     ratio of flops for factor (min/max)     =          0.7920
     ratio of allocated memory (max/min)     =          1.4528
     number of positive pivots               =          291434
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.125000        0.130770
     time (cpu & wall) for ordering          =        0.609375        0.615036
     time (cpu & wall) for other matrix prep =        0.093750        0.084345
     time (cpu & wall) for value input       =        0.281250        0.274172
     time (cpu & wall) for matrix distrib.   =        1.015625        1.023447
     time (cpu & wall) for numeric factor    =        7.406250        8.492801
     computational rate (gflops) for factor  =       57.335517       50.000135
     time (cpu & wall) for numeric solve     =        0.296875        0.608204
     computational rate (gflops) for solve   =        6.583350        3.213450
     effective I/O rate (GB/sec) for solve   =       24.526837       11.971983

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                90-   0      69337088.      529. MB     181042899.     1381. MB
                90-   1      62750720.      479. MB     166717296.     1272. MB
                90-   2      65404928.      499. MB     172461969.     1316. MB
                90-   3      60194816.      459. MB     160640002.     1226. MB
                94-   0       7438336.       57. MB      14850650.      113. MB
                94-   1       6717440.       51. MB      13391104.      102. MB
                94-   2       7471104.       57. MB      14886884.      114. MB
                94-   3       6291456.       48. MB      12555918.       96. MB
                95-   0        655360.        5. MB        638065.        5. MB
                95-   1        557056.        4. MB        552695.        4. MB
                95-   2        622592.        5. MB        606245.        5. MB
                95-   3        655360.        5. MB        624921.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:     288096256.     2198. MB     738968648.     5638. MB


  Solver Memory allocated on core    0       =      331.312 MB
  Solver Memory allocated on core    1       =      243.012 MB
  Solver Memory allocated on core    2       =      282.023 MB
  Solver Memory allocated on core    3       =      228.057 MB
  Total Solver Memory allocated by all cores =     1084.404 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291434
     no. of nonzeroes in lower triangle of a =        21243095
     no. of nonzeroes in the factor l        =       258072137
     ratio of nonzeroes in factor (min/max)  =          0.8112
     number of super nodes                   =            6332
     maximum order of a front matrix         =            5082
     maximum size of a front matrix          =        12915903
     maximum size of a front trapezoid       =         6487998
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.6129D+11
     no. of floating point ops for solve     =      2.9595D+09
     ratio of flops for factor (min/max)     =          0.7485
     ratio of allocated memory (max/min)     =          1.3253
     number of positive pivots               =          291434
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.140625        0.130683
     time (cpu & wall) for ordering          =        0.500000        0.513914
     time (cpu & wall) for other matrix prep =        0.078125        0.077331
     time (cpu & wall) for value input       =        0.281250        0.277925
     time (cpu & wall) for matrix distrib.   =        0.937500        0.962184
     time (cpu & wall) for numeric factor    =        8.546875        8.646000
     computational rate (gflops) for factor  =       53.971437       53.352662
     time (cpu & wall) for numeric solve     =        0.156250        0.159303
     computational rate (gflops) for solve   =       18.940746       18.577764
     effective I/O rate (GB/sec) for solve   =       70.565379       69.213056

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        655360.        5. MB        649145.        5. MB
                95-   1        622592.        5. MB        589957.        5. MB
                95-   2        622592.        5. MB        606919.        5. MB
                95-   3        589824.        4. MB        584575.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2490368.       19. MB       2430596.       19. MB


  Solver Memory allocated on core    0       =      901.218 MB
  Solver Memory allocated on core    1       =      828.632 MB
  Solver Memory allocated on core    2       =      797.292 MB
  Solver Memory allocated on core    3       =      680.032 MB
  Total Solver Memory allocated by all cores =     3207.173 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291434
     no. of nonzeroes in lower triangle of a =        21223556
     no. of nonzeroes in the factor l        =       256784576
     ratio of nonzeroes in factor (min/max)  =          0.8660
     number of super nodes                   =            6335
     maximum order of a front matrix         =            5094
     maximum size of a front matrix          =        12976965
     maximum size of a front trapezoid       =         6772962
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.5903D+11
     no. of floating point ops for solve     =      3.9594D+09
     ratio of flops for factor (min/max)     =          0.8109
     ratio of allocated memory (max/min)     =          1.1993
     number of positive pivots               =          291434
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.125000        0.136154
     time (cpu & wall) for ordering          =        0.640625        0.707033
     time (cpu & wall) for other matrix prep =        0.078125        0.157064
     time (cpu & wall) for value input       =        0.328125        0.385404
     time (cpu & wall) for matrix distrib.   =        0.921875        1.223102
     time (cpu & wall) for numeric factor    =        7.250000        7.415706
     computational rate (gflops) for factor  =       63.314379       61.899606
     time (cpu & wall) for numeric solve     =        0.156250        0.154743
     computational rate (gflops) for solve   =       25.340003       25.586782
     effective I/O rate (GB/sec) for solve   =       94.406359       95.325756

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        655360.        5. MB        650191.        5. MB
                95-   1        622592.        5. MB        615899.        5. MB
                95-   2        622592.        5. MB        600243.        5. MB
                95-   3        589824.        4. MB        565016.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2490368.       19. MB       2431349.       19. MB


  Solver Memory allocated on core    0       =      839.952 MB
  Solver Memory allocated on core    1       =      700.344 MB
  Solver Memory allocated on core    2       =      839.686 MB
  Solver Memory allocated on core    3       =      792.458 MB
  Total Solver Memory allocated by all cores =     3172.440 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291434
     no. of nonzeroes in lower triangle of a =        21223556
     no. of nonzeroes in the factor l        =       256784576
     ratio of nonzeroes in factor (min/max)  =          0.8660
     number of super nodes                   =            6335
     maximum order of a front matrix         =            5094
     maximum size of a front matrix          =        12976965
     maximum size of a front trapezoid       =         6772962
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.5903D+11
     no. of floating point ops for solve     =      3.9594D+09
     ratio of flops for factor (min/max)     =          0.8109
     ratio of allocated memory (max/min)     =          1.1994
     number of positive pivots               =          291434
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.046875        0.058352
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.156250        0.166621
     time (cpu & wall) for matrix distrib.   =        0.484375        0.506422
     time (cpu & wall) for numeric factor    =        7.031250        7.840285
     computational rate (gflops) for factor  =       65.284160       58.547520
     time (cpu & wall) for numeric solve     =        0.156250        0.158217
     computational rate (gflops) for solve   =       25.340003       25.024937
     effective I/O rate (GB/sec) for solve   =       94.406359       93.232553

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        655360.        5. MB        650191.        5. MB
                95-   1        622592.        5. MB        615899.        5. MB
                95-   2        622592.        5. MB        600243.        5. MB
                95-   3        589824.        4. MB        565016.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2490368.       19. MB       2431349.       19. MB


  Solver Memory allocated on core    0       =      839.924 MB
  Solver Memory allocated on core    1       =      700.309 MB
  Solver Memory allocated on core    2       =      839.613 MB
  Solver Memory allocated on core    3       =      792.422 MB
  Total Solver Memory allocated by all cores =     3172.268 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291434
     no. of nonzeroes in lower triangle of a =        21216563
     no. of nonzeroes in the factor l        =       251783768
     ratio of nonzeroes in factor (min/max)  =          0.8624
     number of super nodes                   =            6371
     maximum order of a front matrix         =            4758
     maximum size of a front matrix          =        11321661
     maximum size of a front trapezoid       =         5911641
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.2941D+11
     no. of floating point ops for solve     =      4.9394D+09
     ratio of flops for factor (min/max)     =          0.7849
     ratio of allocated memory (max/min)     =          1.2296
     number of positive pivots               =          291434
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.125000        0.122343
     time (cpu & wall) for ordering          =        0.578125        0.588024
     time (cpu & wall) for other matrix prep =        0.078125        0.079118
     time (cpu & wall) for value input       =        0.265625        0.271467
     time (cpu & wall) for matrix distrib.   =        0.859375        0.854353
     time (cpu & wall) for numeric factor    =        6.187500        6.281735
     computational rate (gflops) for factor  =       69.398931       68.357845
     time (cpu & wall) for numeric solve     =        0.140625        0.144971
     computational rate (gflops) for solve   =       35.124637       34.071539
     effective I/O rate (GB/sec) for solve   =      130.859855      126.936447

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        622592.        5. MB        609773.        5. MB
                95-   1        655360.        5. MB        641727.        5. MB
                95-   2        622592.        5. MB        613199.        5. MB
                95-   3        589824.        4. MB        570101.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2490368.       19. MB       2434800.       19. MB


  Solver Memory allocated on core    0       =      781.857 MB
  Solver Memory allocated on core    1       =      708.106 MB
  Solver Memory allocated on core    2       =      870.666 MB
  Solver Memory allocated on core    3       =      777.891 MB
  Total Solver Memory allocated by all cores =     3138.520 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291434
     no. of nonzeroes in lower triangle of a =        21216563
     no. of nonzeroes in the factor l        =       251783768
     ratio of nonzeroes in factor (min/max)  =          0.8624
     number of super nodes                   =            6371
     maximum order of a front matrix         =            4758
     maximum size of a front matrix          =        11321661
     maximum size of a front trapezoid       =         5911641
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.2941D+11
     no. of floating point ops for solve     =      4.9394D+09
     ratio of flops for factor (min/max)     =          0.7849
     ratio of allocated memory (max/min)     =          1.2296
     number of positive pivots               =          291434
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.125000        0.125091
     time (cpu & wall) for matrix distrib.   =        0.421875        0.430982
     time (cpu & wall) for numeric factor    =        6.125000        6.220293
     computational rate (gflops) for factor  =       70.107084       69.033068
     time (cpu & wall) for numeric solve     =        0.125000        0.134392
     computational rate (gflops) for solve   =       39.515217       36.753691
     effective I/O rate (GB/sec) for solve   =      147.217337      136.929037

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        622592.        5. MB        609773.        5. MB
                95-   1        655360.        5. MB        641727.        5. MB
                95-   2        622592.        5. MB        613199.        5. MB
                95-   3        589824.        4. MB        570101.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2490368.       19. MB       2434800.       19. MB


  Solver Memory allocated on core    0       =      781.857 MB
  Solver Memory allocated on core    1       =      708.106 MB
  Solver Memory allocated on core    2       =      870.666 MB
  Solver Memory allocated on core    3       =      777.891 MB
  Total Solver Memory allocated by all cores =     3138.520 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291426
     no. of nonzeroes in lower triangle of a =        21210339
     no. of nonzeroes in the factor l        =       247255827
     ratio of nonzeroes in factor (min/max)  =          0.8909
     number of super nodes                   =            6246
     maximum order of a front matrix         =            3951
     maximum size of a front matrix          =         7807176
     maximum size of a front trapezoid       =         5019696
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.0870D+11
     no. of floating point ops for solve     =      5.9017D+09
     ratio of flops for factor (min/max)     =          0.8451
     ratio of allocated memory (max/min)     =          1.1905
     number of positive pivots               =          291426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.062500        0.067596
     time (cpu & wall) for ordering          =        0.546875        0.559109
     time (cpu & wall) for other matrix prep =        0.093750        0.080174
     time (cpu & wall) for value input       =        0.125000        0.129446
     time (cpu & wall) for matrix distrib.   =        0.437500        0.445799
     time (cpu & wall) for numeric factor    =        6.359375        6.741513
     computational rate (gflops) for factor  =       64.267842       60.624863
     time (cpu & wall) for numeric solve     =        0.171875        0.165426
     computational rate (gflops) for solve   =       34.337223       35.675745
     effective I/O rate (GB/sec) for solve   =      127.926276      132.913058

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        655360.        5. MB        652032.        5. MB
                95-   1        655360.        5. MB        630898.        5. MB
                95-   2        589824.        4. MB        579971.        4. MB
                95-   3        557056.        4. MB        544897.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2457600.       19. MB       2407798.       18. MB


  Solver Memory allocated on core    0       =      837.087 MB
  Solver Memory allocated on core    1       =      703.157 MB
  Solver Memory allocated on core    2       =      788.961 MB
  Solver Memory allocated on core    3       =      739.060 MB
  Total Solver Memory allocated by all cores =     3068.265 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291426
     no. of nonzeroes in lower triangle of a =        21210339
     no. of nonzeroes in the factor l        =       247255827
     ratio of nonzeroes in factor (min/max)  =          0.8909
     number of super nodes                   =            6246
     maximum order of a front matrix         =            3951
     maximum size of a front matrix          =         7807176
     maximum size of a front trapezoid       =         5019696
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.0870D+11
     no. of floating point ops for solve     =      5.9017D+09
     ratio of flops for factor (min/max)     =          0.8451
     ratio of allocated memory (max/min)     =          1.1905
     number of positive pivots               =          291426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.062500        0.049135
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.109375        0.130688
     time (cpu & wall) for matrix distrib.   =        0.515625        0.503463
     time (cpu & wall) for numeric factor    =        6.437500        6.658301
     computational rate (gflops) for factor  =       63.487892       61.382518
     time (cpu & wall) for numeric solve     =        0.296875        0.296904
     computational rate (gflops) for solve   =       19.879445       19.877496
     effective I/O rate (GB/sec) for solve   =       74.062581       74.055322

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        655360.        5. MB        652032.        5. MB
                95-   1        655360.        5. MB        630898.        5. MB
                95-   2        589824.        4. MB        579971.        4. MB
                95-   3        557056.        4. MB        544897.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2457600.       19. MB       2407798.       18. MB


  Solver Memory allocated on core    0       =      837.065 MB
  Solver Memory allocated on core    1       =      703.114 MB
  Solver Memory allocated on core    2       =      788.800 MB
  Solver Memory allocated on core    3       =      738.979 MB
  Total Solver Memory allocated by all cores =     3067.958 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291426
     no. of nonzeroes in lower triangle of a =        21183897
     no. of nonzeroes in the factor l        =       251153709
     ratio of nonzeroes in factor (min/max)  =          0.8176
     number of super nodes                   =            6319
     maximum order of a front matrix         =            4512
     maximum size of a front matrix          =        10181328
     maximum size of a front trapezoid       =         5318691
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.1795D+11
     no. of floating point ops for solve     =      6.8792D+09
     ratio of flops for factor (min/max)     =          0.7329
     ratio of allocated memory (max/min)     =          1.3507
     number of positive pivots               =          291426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.109157
     time (cpu & wall) for ordering          =        0.640625        0.703010
     time (cpu & wall) for other matrix prep =        0.109375        0.103296
     time (cpu & wall) for value input       =        0.250000        0.253933
     time (cpu & wall) for matrix distrib.   =        1.000000        1.037375
     time (cpu & wall) for numeric factor    =        8.109375       13.779134
     computational rate (gflops) for factor  =       51.539600       30.332381
     time (cpu & wall) for numeric solve     =        0.375000        0.891555
     computational rate (gflops) for solve   =       18.344440        7.715922
     effective I/O rate (GB/sec) for solve   =       68.343789       28.746331

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                90-   0      60653568.      463. MB     156485074.     1194. MB
                90-   1      58392576.      446. MB     155595595.     1187. MB
                90-   2      70909952.      541. MB     188851987.     1441. MB
                90-   3      67502080.      515. MB     180944656.     1380. MB
                94-   0       6848512.       52. MB      13656342.      104. MB
                94-   1       6094848.       46. MB      12131712.       93. MB
                94-   2       7438336.       57. MB      14867610.      113. MB
                94-   3       7438336.       57. MB      14836602.      113. MB
                95-   0        622592.        5. MB        600280.        5. MB
                95-   1        622592.        5. MB        613011.        5. MB
                95-   2        622592.        5. MB        611207.        5. MB
                95-   3        622592.        5. MB        598176.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:     287768576.     2196. MB     739792252.     5644. MB


  Solver Memory allocated on core    0       =      318.064 MB
  Solver Memory allocated on core    1       =      235.474 MB
  Solver Memory allocated on core    2       =      281.311 MB
  Solver Memory allocated on core    3       =      243.675 MB
  Total Solver Memory allocated by all cores =     1078.523 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291426
     no. of nonzeroes in lower triangle of a =        21183897
     no. of nonzeroes in the factor l        =       251153709
     ratio of nonzeroes in factor (min/max)  =          0.8176
     number of super nodes                   =            6319
     maximum order of a front matrix         =            4512
     maximum size of a front matrix          =        10181328
     maximum size of a front trapezoid       =         5318691
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.1795D+11
     no. of floating point ops for solve     =      6.8792D+09
     ratio of flops for factor (min/max)     =          0.7329
     ratio of allocated memory (max/min)     =          1.3507
     number of positive pivots               =          291426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.046875        0.050606
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.125000        0.123921
     time (cpu & wall) for matrix distrib.   =        0.531250        0.535611
     time (cpu & wall) for numeric factor    =        6.968750        7.707998
     computational rate (gflops) for factor  =       59.975454       54.223410
     time (cpu & wall) for numeric solve     =        0.359375        0.759625
     computational rate (gflops) for solve   =       19.142024        9.056005
     effective I/O rate (GB/sec) for solve   =       71.315258       33.738925

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                90-   0      60653568.      463. MB     312970148.     2388. MB
                90-   1      58392576.      446. MB     311191190.     2374. MB
                90-   2      70909952.      541. MB     377703974.     2882. MB
                90-   3      67502080.      515. MB     361889312.     2761. MB
                94-   0       6848512.       52. MB      27293520.      208. MB
                94-   1       6094848.       46. MB      24263424.      185. MB
                94-   2       7438336.       57. MB      29717406.      227. MB
                94-   3       7438336.       57. MB      29659914.      226. MB
                95-   0        622592.        5. MB        600280.        5. MB
                95-   1        622592.        5. MB        613011.        5. MB
                95-   2        622592.        5. MB        611207.        5. MB
                95-   3        622592.        5. MB        598176.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:     287768576.     2196. MB    1477111562.    11269. MB


  Solver Memory allocated on core    0       =      317.982 MB
  Solver Memory allocated on core    1       =      235.412 MB
  Solver Memory allocated on core    2       =      281.122 MB
  Solver Memory allocated on core    3       =      243.580 MB
  Total Solver Memory allocated by all cores =     1078.096 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291426
     no. of nonzeroes in lower triangle of a =        21133875
     no. of nonzeroes in the factor l        =       256153476
     ratio of nonzeroes in factor (min/max)  =          0.7634
     number of super nodes                   =            6362
     maximum order of a front matrix         =            4758
     maximum size of a front matrix          =        11321661
     maximum size of a front trapezoid       =         5695326
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.4545D+11
     no. of floating point ops for solve     =      7.8766D+09
     ratio of flops for factor (min/max)     =          0.6566
     ratio of allocated memory (max/min)     =          1.3897
     number of positive pivots               =          291426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.103361
     time (cpu & wall) for ordering          =        0.656250        0.657499
     time (cpu & wall) for other matrix prep =        0.078125        0.090858
     time (cpu & wall) for value input       =        0.250000        0.257975
     time (cpu & wall) for matrix distrib.   =        0.859375        0.893732
     time (cpu & wall) for numeric factor    =        6.828125        9.677459
     computational rate (gflops) for factor  =       65.236810       46.029136
     time (cpu & wall) for numeric solve     =        0.281250        0.680356
     computational rate (gflops) for solve   =       28.005797       11.577219
     effective I/O rate (GB/sec) for solve   =      104.338006       43.131926

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                90-   0      62291968.      475. MB     161387782.     1231. MB
                90-   1      56524800.      431. MB     150116389.     1145. MB
                90-   2      73629696.      562. MB     196679386.     1501. MB
                90-   3      70156288.      535. MB     188353096.     1437. MB
                94-   0       6815744.       52. MB      13599042.      104. MB
                94-   1       5701632.       44. MB      11392596.       87. MB
                94-   2       7569408.       58. MB      15134856.      115. MB
                94-   3       7634944.       58. MB      15222918.      116. MB
                95-   0        622592.        5. MB        603011.        5. MB
                95-   1        589824.        4. MB        585615.        4. MB
                95-   2        655360.        5. MB        631285.        5. MB
                95-   3        622592.        5. MB        608825.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:     292814848.     2234. MB     754314801.     5755. MB


  Solver Memory allocated on core    0       =      317.456 MB
  Solver Memory allocated on core    1       =      228.432 MB
  Solver Memory allocated on core    2       =      283.204 MB
  Solver Memory allocated on core    3       =      246.825 MB
  Total Solver Memory allocated by all cores =     1075.917 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          291426
     no. of nonzeroes in lower triangle of a =        21102411
     no. of nonzeroes in the factor l        =       251648883
     ratio of nonzeroes in factor (min/max)  =          0.8530
     number of super nodes                   =            6279
     maximum order of a front matrix         =            4776
     maximum size of a front matrix          =        11407476
     maximum size of a front trapezoid       =         6244185
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      4.3086D+11
     no. of floating point ops for solve     =      8.8565D+09
     ratio of flops for factor (min/max)     =          0.7833
     ratio of allocated memory (max/min)     =          1.3300
     number of positive pivots               =          291426
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.093750        0.135602
     time (cpu & wall) for ordering          =        0.640625        0.641335
     time (cpu & wall) for other matrix prep =        0.093750        0.096259
     time (cpu & wall) for value input       =        0.265625        0.346783
     time (cpu & wall) for matrix distrib.   =        0.968750        2.058412
     time (cpu & wall) for numeric factor    =        6.796875       13.799733
     computational rate (gflops) for factor  =       63.390778       31.222285
     time (cpu & wall) for numeric solve     =        0.437500        0.821495
     computational rate (gflops) for solve   =       20.243323       10.780892
     effective I/O rate (GB/sec) for solve   =       75.418242       40.165139

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                90-   0      61177856.      467. MB     159081664.     1214. MB
                90-   1      59801600.      456. MB     159536251.     1217. MB
                90-   2      67239936.      513. MB     178456114.     1362. MB
                90-   3      69861376.      533. MB     187251640.     1429. MB
                94-   0       6684672.       51. MB      13314420.      102. MB
                94-   1       6160384.       47. MB      12301794.       94. MB
                94-   2       7143424.       54. MB      14269920.      109. MB
                94-   3       7700480.       59. MB      15388758.      117. MB
                95-   0        622592.        5. MB        590783.        5. MB
                95-   1        622592.        5. MB        619423.        5. MB
                95-   2        622592.        5. MB        591953.        5. MB
                95-   3        622592.        5. MB        609956.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:     288260096.     2199. MB     742012676.     5661. MB


  Solver Memory allocated on core    0       =      314.772 MB
  Solver Memory allocated on core    1       =      236.678 MB
  Solver Memory allocated on core    2       =      274.934 MB
  Solver Memory allocated on core    3       =      247.874 MB
  Total Solver Memory allocated by all cores =     1074.259 MB

